### ISSUE TITLE
interactive, not login shell support

### ISSUE THREAD

**Issue by PSkarzynski-SkyCash** [tecris/ansible-maven#17]
Task
> - name: Maven path configuration

will not work for not login shells (e.g. when role is used with docker containers), where /etc/profile is not used.
Modifying ~/.bashrc solves the issue:
```
- name: Maven path configuration
  blockinfile:
    path: /root/.bashrc
    block: |
      M2_HOME={{maven_home_parent_directory}}/apache-maven-{{maven_version}}
      PATH=$PATH:$M2_HOME/bin
    state: present
```
